apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-infra
  namespace: flux-system
spec:
  interval: 5m
  path: ./flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: devops-test-repo
    namespace: flux-system
  wait: true
  timeout: 3m
