apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-app
  namespace: raw-app
spec:
  kubernetes.io/ingress.class: "gce"
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-app
                port:
                  number: 80
