apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: node-app
  namespace: flux-system
spec:
  image: armansaa/devops-test-pena
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: node-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: node-app
  filterTags:
    pattern: '^node\.prod-[a-f0-9]+-(?P<ts>[0-9]{12})$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: node-app-automation
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: devops-test-repo
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: 'Update image to {{range .Changed.Changes}}{{println .OldValue "->" .NewValue}}{{end}}'
    push:
      branch: main
  update:
    path: ./gitops
    strategy: Setters
