---
- name: Install Node.js repository
  shell: curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Install PM2 globally
  npm:
    name: pm2
    global: yes
    state: present

- name: Install PM2 systemd unit (no-daemon)
  template:
    src: pm2.service.j2
    dest: /etc/systemd/system/pm2-{{ ansible_user }}.service
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Reload systemd
  systemd:
    daemon_reload: true
  become: true

- name: Enable and start PM2 service
  systemd:
    name: pm2-{{ ansible_user }}
    enabled: true
    state: started
  become: true

- name: Save PM2 process list
  shell: pm2 save
  become_user: "{{ ansible_user }}"
