apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops-monitoring
  namespace: flux-system
spec:
  interval: 5m
  path: ./gitops/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: devops-test-repo
    namespace: flux-system
  wait: true
  timeout: 10m
