apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops-monitoring-scrape
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: gitops-monitoring
      namespace: flux-system
  path: ./gitops/monitoring-scrape
  prune: true
  sourceRef:
    kind: GitRepository
    name: devops-test-repo
    namespace: flux-system
  wait: true
  timeout: 5m
