apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources/
  - image-automation/
  - gitops-helm-kustomization.yaml
  - gitops-raw-kustomization.yaml
  - gitops-monitoring-kustomization.yaml
  - gitops-monitoring-scrape-kustomization.yaml
